Correct indention of protect-master gh action

diff --git a/.github/workflows/protect-master.yml b/.github/workflows/protect-master.yml
--- a/.github/workflows/protect-master.yml
+++ b/.github/workflows/protect-master.yml
@@ -5,11 +5,11 @@ on:
     branches:
       - master
 
-  jobs:
-    check-branch:
-      runs-on: ubuntu-latest
-      steps:
-        - name: Check branch
-          run: |
-            echo "Error: Pull request against master is prohibited"
-            exit 1
+jobs:
+  check-branch:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check branch
+        run: |
+          echo "Error: Pull request against master is prohibited"
+          exit 1
